CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE IF NOT EXISTS stations (
  node_id text PRIMARY KEY,
  latest_update_timestamp timestamptz,
  mft_name text,
  trading_name text,
  brand_name text,
  is_motorway_service_station boolean,
  is_supermarket_service_station boolean,
  public_phone_number text,
  temporary_closure boolean,
  permanent_closure boolean,
  permanent_closure_date text,
  location_postcode text,
  location_address_line_1 text,
  location_address_line_2 text,
  location_city text,
  location_county text,
  location_country text,
  location_latitude double precision,
  location_longitude double precision,
  fuel_price_e5 numeric(8,4),
  fuel_price_e10 numeric(8,4),
  fuel_price_b7p numeric(8,4),
  fuel_price_b7s numeric(8,4),
  fuel_price_b10 numeric(8,4),
  fuel_price_hvo numeric(8,4),
  monday_open_time time,
  monday_close_time time,
  monday_is_24_hours boolean,
  tuesday_open_time time,
  tuesday_close_time time,
  tuesday_is_24_hours boolean,
  wednesday_open_time time,
  wednesday_close_time time,
  wednesday_is_24_hours boolean,
  thursday_open_time time,
  thursday_close_time time,
  thursday_is_24_hours boolean,
  friday_open_time time,
  friday_close_time time,
  friday_is_24_hours boolean,
  saturday_open_time time,
  saturday_close_time time,
  saturday_is_24_hours boolean,
  sunday_open_time time,
  sunday_close_time time,
  sunday_is_24_hours boolean,
  bank_holiday_standard_open_time time,
  bank_holiday_standard_close_time time,
  bank_holiday_standard_is_24_hours boolean,
  amenity_adblue_pumps boolean,
  amenity_adblue_packaged boolean,
  amenity_lpg_pumps boolean,
  amenity_car_wash boolean,
  amenity_air_pump_or_screenwash boolean,
  amenity_water_filling boolean,
  amenity_twenty_four_hour_fuel boolean,
  amenity_customer_toilets boolean,
  geom geography(Point, 4326)
);

CREATE INDEX IF NOT EXISTS stations_geom_gix ON stations USING GIST (geom);
CREATE INDEX IF NOT EXISTS stations_brand_name_idx ON stations (brand_name);
CREATE INDEX IF NOT EXISTS stations_postcode_idx ON stations (location_postcode);
